### ISSUE TITLE
PLease: for the love of Odin, someone write some tests for this thing.

### ISSUE THREAD

**Issue by codyloyd** [codyloyd/odin-bot-js#6]
lol

but seriously.....

**Comment by arun1595** [comment]
https://jasmine.github.io/

**Comment by codyloyd** [comment]
ha.. I know about Jasmine.. I've used it before.

I'm _not_ sure, however, how to test bot responses.. how would I check to see if something is being "sent"

**Comment by arun1595** [comment]
I don't think we should test whether something is sent(that depends on the internet which is a dependency). Instead, we should test the message that is being sent. We might want to restructure the code a bit to facilitate the testing.

Thoughts?
